ECommerce/Models/Lot.cs
using ECommerce.Data.Base;
using ECommerce.Data.Enums;
using System.ComponentModel.DataAnnotations;

namespace ECommerce.Models
{
    public class Lot:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Picture URL")]
        [Required(ErrorMessage ="Picture is required")]
        public string Picture { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50,MinimumLength =4, ErrorMessage ="Name must be between 4 and 50 characters")]
        public string Name { get; set; }

        [Display(Name = "Type")]
        [Required(ErrorMessage = "Type is required")]
        public LotType Type { get; set;}

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set;}

        [Display(Name = "Deal Type")]
        [Required(ErrorMessage = "Deal Type is required")]
        public DealType DealType { get; set; }

        [Display(Name = "Status")]
        public bool Status { get; set; }

        [Display(Name = "PublishDate")]
        public DateTime PublishDate { get; set; }

    }
}

ECommerce/Controllers/LotsController.cs
using ECommerce.Data.Cart;
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class LotsController : Controller
    {
        private readonly ILotsService _service;

        public LotsController(ILotsService service)
        {
            _service= service;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAll());
        }
        
        public async Task<IActionResult> Filter(string searchString)
        {
            var allLots = await _service.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allLots.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
            return View("Index", allLots);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Picture,Name,Type,Description,DealType")]Lot lot)
        {
            if (!ModelState.IsValid)
            {
                return View(lot);
            }
            await _service.Add(lot);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var lotDetails = await _service.GetById(id);

            if (lotDetails == null) return View("NotFound");
            return View(lotDetails);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var lotDetails = await _service.GetById(id);
            if (lotDetails == null) return View("NotFound");
            return View(lotDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Picture,Name,Type,Description,DealType")] Lot lot)
        {
            if (!ModelState.IsValid)
            {
                return View(lot);
            }
            await _service.Update(lot, id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var lotDetails = await _service.GetById(id);
            if (lotDetails == null) return View("NotFound");
            return View(lotDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lotDetails = await _service.GetById(id);
            if (lotDetails == null) return View("NotFound");

            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ECommerce/Controllers/OrdersController.cs
using ECommerce.Data.Cart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ECommerce.Data.Services;
using ECommerce.Data.ViewModels;

namespace ECommerce.Controllers
{
    //[Authorize]

    public class OrdersController : Controller
    {
        private readonly ILotsService _lotsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(ILotsService lotsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _lotsService = lotsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _lotsService.GetById(id);

            if (item != null)
            {
                //error
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _lotsService.GetById(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrders()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrdersAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        public async Task<IActionResult> CreateItemForExchange(int id)
        {
            var item = await _lotsService.GetById(id);

            var cartItem = _shoppingCart.GetShoppingCartItem(id);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(cartItem, userId, userEmailAddress);

            if (item != null)
            { 
                _shoppingCart.RemoveItemFromCart(item);
            }
            return View("OrderCompletedWithExchangeItem");
        }

        public async Task<IActionResult> CompleteOrder(int id)
        {
            var item = await _lotsService.GetById(id);

            var cartItem = _shoppingCart.GetShoppingCartItem(id);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(cartItem, userId, userEmailAddress);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return View("OrderCompleted");
        }
    }
}

ECommerce/Controllers/WishListController.cs
using ECommerce.Data.Cart;
using ECommerce.Data.Services;
using ECommerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ECommerce.Data.WishList;

namespace ECommerce.Controllers
{
    public class WishListController : Controller
    {
        private readonly ILotsService _lotsService;
        private readonly IWishListService _wishListService;
        private readonly WishList _wishList;

        public WishListController(ILotsService lotsService, IWishListService wishListService, WishList wishList)
        {
            _lotsService = lotsService;
            _wishListService = wishListService;
            _wishList = wishList;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var items = await _wishListService.GetWishListByUserIdAndRoleAsync(userId);
            return View(items);
        }

        public IActionResult WishList()
        {
            var items = _wishList.GetWishListItems();
            _wishList.WishListItems = items;

            var response = new WishListViewModel()
            {
                WishList = _wishList
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToWishList(int id)
        {
            var item = await _lotsService.GetById(id);

            if (item != null)
            {
                _wishList.AddItemToWishList(item);
            }
            return RedirectToAction(nameof(WishList));
        }

        public async Task<IActionResult> RemoveItemFromWishList(int id)
        {
            var item = await _lotsService.GetById(id);

            if (item != null)
            {
                _wishList.RemoveItemFromWishList(item);
            }
            return RedirectToAction(nameof(WishList));
        }
    }
}

ECommerce/Views/Lots/Create.cshtml
@model Lot

@{
    ViewData["Title"] = "Add a new Lot";
}

<div class="row-text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a new Lot</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="PicturePreview" />
                    </div>
                <div class="form-group">
                    <label asp-for="Picture" class="control-label"></label>
                    <input asp-for="Picture" class="form-control"/>
                    <span asp-validation-for="Picture" class ="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="Name" clas s= "control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                        <select asp-for="Type" class="form-control">
                            <option value="">Select Type</option>
                            <option value="Toys">Toys</option>
                            <option value="Clothing">Clothing</option>
                            <option value="Rust">Rust</option>
                            <option value="Appliances">Appliances</option>
                        </select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                    <div class="form-group">
                        <label asp-for="DealType" class="control-label"></label>
                        <select asp-for="DealType" class="form-control">
                            <option value="">Select Deal Type</option>
                            <option value="Exchange">Exchange</option>
                            <option value="Chargeless">Chargeless</option>
                        </select>
                        <span asp-validation-for="DealType" class="text-danger"></span>
                    </div>
                    <span style="padding: 5px;"></span>
                    <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function (){
            var output = document.getElementById('PicturePreview')
            output.src = $("#Picture").val();
        })

        $("#Picture").on("change", function(){
            var output = document.getElementById('PicturePreview')
            output.src = $(this).val();
        })
    </script>
}

ECommerce/Views/Lots/Delete.cshtml
@model Lot

@{
    ViewData["Title"] = "Delete a Lot";
}

<div class="row-text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 150px" id="PicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label"></label>
                        <input asp-for="Picture" class="form-control" readonly/>
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" clas s="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <input asp-for="Type" class="form-control" readonly />
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DealType" class="control-label"></label>
                    <input asp-for="DealType" class="form-control" readonly />
                    <span asp-validation-for="DealType" class="text-danger"></span>
                    </div>
                <span style="padding: 5px;"></span>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <form asp-action="Delete" style="padding-right: 25px">
                                <input type="hidden" asp-for="Id"/>
                                <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
                            </form>
                        </div>
                        <div class="col-auto">
                            <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PicturePreview')
            output.src = $("Picture").val();
        })
    </script>
}

ECommerce/Views/Lots/Details.cshtml
@model Lot

@{
    ViewData["Title"] = "Add a new Lot";
}

<div class="row-text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="col-md-4 offset-4 text-center">
                    <img width="100%" id="PicturePreview" />
                </div>
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label"></label>
                        <input asp-for="Picture" class="form-control" readonly/>
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" clas s="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <input asp-for="Type" class="form-control" readonly />
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DealType" class="control-label"></label>
                        <input asp-for="DealType" class="form-control" readonly />
                        <span asp-validation-for="DealType" class="text-danger"></span>
                    </div>
                    <span style="padding: 5px;"></span>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PicturePreview')
            output.src = $("#Picture").val();
        })
    </script>
}

ECommerce/Views/Lots/Edit.cshtml
@model Lot

@{
    ViewData["Title"] = "Update a new Lot";
}

<div class="row-text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update a new Lot</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="PicturePreview" />
                    </div>
                <div class="form-group">
                    <label asp-for="Picture" class="control-label"></label>
                    <input asp-for="Picture" class="form-control"/>
                    <span asp-validation-for="Picture" class ="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="Name" clas s= "control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <select asp-for="Type" class="form-control">
                            <option value="">Select Type</option>
                            <option value="Toys">Toys</option>
                            <option value="Clothing">Clothing</option>
                            <option value="Rust">Rust</option>
                            <option value="Appliances">Appliances</option>
                        </select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                    <div class="form-group">
                        <label asp-for="DealType" class="control-label"></label>
                        <select asp-for="DealType" class="form-control">
                            <option value="">Select Deal Type</option>
                            <option value="Exchange">Exchange</option>
                            <option value="Chargeless">Chargeless</option>
                        </select>
                        <span asp-validation-for="DealType" class="text-danger"></span>
                    </div>
                    <span style="padding: 5px;"></span>
                    <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-outline-success" />
                    <a class="btn btn-outline-secondary float-end" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function (){
            var output = document.getElementById('PicturePreview')
            output.src = $("#Picture").val();
        });
        $("#Picture").on("change", function(){
            var output = document.getElementById('PicturePreview')
            output.src = $(this).val();
        });
    </script>
}

ECommerce/Views/Lots/Index.cshtml
@model IEnumerable<Lot>

@{
    ViewData["Title"] = "List of Lots";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.Picture" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                        <p class="card-text">@item.Description</p>
                        <p class="card-text"><b>Name: </b>@item.Name</p>
                        <p class="card-text"><b>Category: </b>@item.Type</p>
                            <p class="card-text"><b>Deal Type: </b>@item.DealType</p>
                            <p class="card-text"><b>PublishDate: </b>@item.PublishDate</p>
                            <p class="card-text ">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                            {
                                    <a class="btn btn-success text-white"
                               asp-controller="Orders"
                               asp-action="AddItemToShoppingCart"
                               asp-route-id="@item.Id">
                                        <i class="bi bi-cart-plus"></i> Create a deal
                                    </a>
                                    <a class="btn btn-success text-white"
                               asp-controller="WishList"
                               asp-action="AddItemToWishList"
                               asp-route-id="@item.Id">
                                        <i class="bi bi-bookmark-plus-fill"></i> Add to WishList
                                    </a>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    <a class="btn btn-outline-danger" asp-controller="Lots" asp-action="Delete" asp-route-id="@item.Id">
                                        <i class="bi bi-eye-fill"></i> 
                                        Delete
                                    </a>
                                }
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Lots")